name: Simple JS Action
on: [push]
jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
    - name : js1
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: Pradip