name: First Command
on: [push]

jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  steps:
    - name: shell command
      run: echo "Hello World"
    - name : multi line command
      run: |
       node -v
       python -v  
    - name: python command
      run: |
       print("Hello from Python")
       print("Hello again")
      shell: python

 run-on-windows:
  runs-on: windows-latest
  steps:
  - name: run bash
    run: pwd
    shell: bash

